/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import views.frmLogin;
import components.TableModelKlijenti;
import components.TableModelPrijemnica;
import controller.CommunicationController;
import domain.Racun;
import domain.Radnik;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.TableColumnModel;
import javax.swing.table.TableModel;

/**
 *
 * @author Stefan
 */
public class frmMenu extends javax.swing.JFrame {
    Radnik radnik;
    /**
     * Creates new form frmMenu
     */
    public frmMenu(Radnik radnik) {
        this.radnik=radnik;
        initComponents();
        uPozadini();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabelPrezimeRadnika = new javax.swing.JLabel();
        jLabelImeRadnika = new javax.swing.JLabel();
        jBtnStampajPrijemnicu = new javax.swing.JButton();
        jBtnStampajRacun = new javax.swing.JButton();
        jBtnPretraziPrtljag = new javax.swing.JButton();
        jBtnIzvestajOTransakcijama = new javax.swing.JButton();
        jBtnDodajTransakciju4 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPrijemnice = new javax.swing.JTable();
        jLblKolicina = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabelKorisnickoImeRadnika = new javax.swing.JLabel();
        jLabelImeRadnika1 = new javax.swing.JLabel();
        jLabelPrezimeRadnika1 = new javax.swing.JLabel();
        jLabelKorisnickoImeRadnika1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jBtnObrisiPrijemnicu = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenuItemOdjava = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jPanel1FocusGained(evt);
            }
        });
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel1MouseExited(evt);
            }
        });
        jPanel1.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                jPanel1ComponentShown(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/profile.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("DialogInput", 1, 24)); // NOI18N
        jLabel2.setText("Radnik:");

        jLabelPrezimeRadnika.setFont(new java.awt.Font("DialogInput", 1, 18)); // NOI18N
        jLabelPrezimeRadnika.setText("Prezime");

        jLabelImeRadnika.setFont(new java.awt.Font("DialogInput", 1, 18)); // NOI18N
        jLabelImeRadnika.setText("Ime");

        jBtnStampajPrijemnicu.setFont(new java.awt.Font("DialogInput", 1, 14)); // NOI18N
        jBtnStampajPrijemnicu.setText("Ispisi prijemnice");
        jBtnStampajPrijemnicu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnStampajPrijemnicuActionPerformed(evt);
            }
        });

        jBtnStampajRacun.setFont(new java.awt.Font("DialogInput", 1, 14)); // NOI18N
        jBtnStampajRacun.setText("Kreiraj racun");
        jBtnStampajRacun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnStampajRacunActionPerformed(evt);
            }
        });

        jBtnPretraziPrtljag.setFont(new java.awt.Font("DialogInput", 1, 14)); // NOI18N
        jBtnPretraziPrtljag.setText("Pretrazi prljag");
        jBtnPretraziPrtljag.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnPretraziPrtljagActionPerformed(evt);
            }
        });

        jBtnIzvestajOTransakcijama.setFont(new java.awt.Font("DialogInput", 1, 14)); // NOI18N
        jBtnIzvestajOTransakcijama.setText("Izvestaj o transakcijama");
        jBtnIzvestajOTransakcijama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnIzvestajOTransakcijamaActionPerformed(evt);
            }
        });

        jBtnDodajTransakciju4.setFont(new java.awt.Font("DialogInput", 1, 14)); // NOI18N
        jBtnDodajTransakciju4.setText("Dodaj prijemnicu");
        jBtnDodajTransakciju4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jBtnDodajTransakciju4MouseExited(evt);
            }
        });
        jBtnDodajTransakciju4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnDodajTransakciju4ActionPerformed(evt);
            }
        });

        tblPrijemnice.setFont(new java.awt.Font("DialogInput", 1, 14)); // NOI18N
        tblPrijemnice.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tblPrijemnice.setRowHeight(28);
        tblPrijemnice.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblPrijemniceMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblPrijemnice);

        jLblKolicina.setFont(new java.awt.Font("DialogInput", 1, 18)); // NOI18N
        jLblKolicina.setText("Kolicina");

        jLabel6.setFont(new java.awt.Font("DialogInput", 1, 18)); // NOI18N
        jLabel6.setText("Kolicina:");

        jLabel7.setFont(new java.awt.Font("DialogInput", 1, 18)); // NOI18N
        jLabel7.setText("kom.");

        jLabelKorisnickoImeRadnika.setFont(new java.awt.Font("DialogInput", 1, 18)); // NOI18N
        jLabelKorisnickoImeRadnika.setText("Korisnicko");

        jLabelImeRadnika1.setFont(new java.awt.Font("DialogInput", 1, 18)); // NOI18N
        jLabelImeRadnika1.setText("Ime:");

        jLabelPrezimeRadnika1.setFont(new java.awt.Font("DialogInput", 1, 18)); // NOI18N
        jLabelPrezimeRadnika1.setText("Prezime:");

        jLabelKorisnickoImeRadnika1.setFont(new java.awt.Font("DialogInput", 1, 18)); // NOI18N
        jLabelKorisnickoImeRadnika1.setText("Korisnicko ime:");

        jLabel5.setFont(new java.awt.Font("DialogInput", 1, 24)); // NOI18N
        jLabel5.setText("Trenutno stanje na skladistu:");

        jBtnObrisiPrijemnicu.setFont(new java.awt.Font("DialogInput", 1, 14)); // NOI18N
        jBtnObrisiPrijemnicu.setText("Obrisi prljag");
        jBtnObrisiPrijemnicu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnObrisiPrijemnicuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(jBtnDodajTransakciju4, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jBtnStampajPrijemnicu)
                        .addGap(27, 27, 27)
                        .addComponent(jBtnStampajRacun, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jBtnObrisiPrijemnicu, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jBtnPretraziPrtljag, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jBtnIzvestajOTransakcijama))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(15, 15, 15)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(158, 158, 158))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelKorisnickoImeRadnika1, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabelPrezimeRadnika1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabelImeRadnika1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelKorisnickoImeRadnika, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabelPrezimeRadnika, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 187, Short.MAX_VALUE)
                                        .addComponent(jLabelImeRadnika, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 695, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(42, 42, 42)
                        .addComponent(jLblKolicina)
                        .addGap(30, 30, 30)
                        .addComponent(jLabel7)
                        .addGap(7, 7, 7))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(158, 158, 158))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(29, 29, 29)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabelImeRadnika)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabelPrezimeRadnika)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabelKorisnickoImeRadnika))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabelImeRadnika1)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabelPrezimeRadnika1)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabelKorisnickoImeRadnika1))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1))))
                        .addGap(87, 87, 87)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jBtnStampajPrijemnicu, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBtnStampajRacun, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBtnDodajTransakciju4, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(80, 80, 80)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jBtnPretraziPrtljag, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBtnIzvestajOTransakcijama, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBtnObrisiPrijemnicu, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 529, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLblKolicina)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))))
                .addContainerGap(39, Short.MAX_VALUE))
        );

        jLabel3.setText("jLabel3");

        jLabel4.setText("jLabel4");

        jMenu2.setText("Odjava");

        jMenuItemOdjava.setText("Odjava");
        jMenuItemOdjava.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemOdjavaActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItemOdjava);

        jMenuBar2.add(jMenu2);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnStampajPrijemnicuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnStampajPrijemnicuActionPerformed
        uPozadini();  
    }//GEN-LAST:event_jBtnStampajPrijemnicuActionPerformed

    private void jBtnStampajRacunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnStampajRacunActionPerformed
        if(tblPrijemnice.getSelectedRow()!=-1){    
            try {
                Racun racun=CommunicationController.getInstance().vratiTrenutnoStanje().get(tblPrijemnice.getSelectedRow());
                JDialog dialog=new JDialog();
                JPanel panel=new frmStampajRacun(racun);
                dialog.add(panel);
                dialog.pack();
                dialog.setLocationByPlatform(true);
                dialog.setVisible(true);
            } catch (IOException ex) {
                Logger.getLogger(frmMenu.class.getName()).log(Level.SEVERE, null, ex);
            }
            
        }else{
            JOptionPane.showMessageDialog(this, "Potrebno je da selektujete racun!");
        }
    }//GEN-LAST:event_jBtnStampajRacunActionPerformed

    private void jBtnPretraziPrtljagActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnPretraziPrtljagActionPerformed
        JDialog dialog=new JDialog(this,"Pretraga prtljaga",true);
        JPanel panel=new frmPretraga();
        dialog.add(panel);
        dialog.pack();
        dialog.setLocationByPlatform(true);
        dialog.show();
    }//GEN-LAST:event_jBtnPretraziPrtljagActionPerformed

    private void jBtnIzvestajOTransakcijamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnIzvestajOTransakcijamaActionPerformed
       JDialog dialog=new JDialog();
       JPanel panel=new frmIzvestajSvihTransakcija();
       dialog.add(panel);
       dialog.pack();
       dialog.setLocationByPlatform(true);
       dialog.setVisible(true);
    }//GEN-LAST:event_jBtnIzvestajOTransakcijamaActionPerformed

    private void jBtnDodajTransakciju4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnDodajTransakciju4ActionPerformed
        JFrame transakcija=new frmTransakcija(radnik);
        transakcija.pack();
        transakcija.setLocationByPlatform(true);
        transakcija.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_jBtnDodajTransakciju4ActionPerformed

    private void jMenuItemOdjavaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemOdjavaActionPerformed
        dispose();
        JFrame login=new frmLogin();
        login.setVisible(true);
    }//GEN-LAST:event_jMenuItemOdjavaActionPerformed

    private void jPanel1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseEntered
       
    }//GEN-LAST:event_jPanel1MouseEntered

    private void jPanel1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseExited
        
    }//GEN-LAST:event_jPanel1MouseExited

    private void jPanel1ComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jPanel1ComponentShown
        
    }//GEN-LAST:event_jPanel1ComponentShown

    private void jPanel1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPanel1FocusGained
        
    }//GEN-LAST:event_jPanel1FocusGained

    private void jBtnDodajTransakciju4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnDodajTransakciju4MouseExited
        
    }//GEN-LAST:event_jBtnDodajTransakciju4MouseExited

    private void tblPrijemniceMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPrijemniceMouseClicked
        
    }//GEN-LAST:event_tblPrijemniceMouseClicked

    private void jPanel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseClicked
        
    }//GEN-LAST:event_jPanel1MouseClicked

    private void jBtnObrisiPrijemnicuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnObrisiPrijemnicuActionPerformed
        if(tblPrijemnice.getSelectedRow()!=-1){    
            try {    
                Racun racun=CommunicationController.getInstance().vratiTrenutnoStanje().get(tblPrijemnice.getSelectedRow());
                Racun racunRez=CommunicationController.getInstance().obrisiPrijemnicu(racun);
                try {
                    JOptionPane.showMessageDialog(this, "Sistem je obrisao prijemnicu. \n Prijemnica : "+racunRez.getIdRacuna());
                    uPozadini();
                } catch (Exception ex) {
                    JOptionPane.showMessageDialog(this, "Sistem ne moze da obrise prijemnicu. \n Prijemnica : "+racunRez.getIdRacuna());
                }
                
            } catch (IOException ex) {
                Logger.getLogger(frmMenu.class.getName()).log(Level.SEVERE, null,ex);
            }
            
        }else{
            JOptionPane.showMessageDialog(this, "Potrebno je da selektujete racun!");
        }
    }//GEN-LAST:event_jBtnObrisiPrijemnicuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnDodajTransakciju4;
    private javax.swing.JButton jBtnIzvestajOTransakcijama;
    private javax.swing.JButton jBtnObrisiPrijemnicu;
    private javax.swing.JButton jBtnPretraziPrtljag;
    private javax.swing.JButton jBtnStampajPrijemnicu;
    private javax.swing.JButton jBtnStampajRacun;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabelImeRadnika;
    private javax.swing.JLabel jLabelImeRadnika1;
    private javax.swing.JLabel jLabelKorisnickoImeRadnika;
    private javax.swing.JLabel jLabelKorisnickoImeRadnika1;
    private javax.swing.JLabel jLabelPrezimeRadnika;
    private javax.swing.JLabel jLabelPrezimeRadnika1;
    private javax.swing.JLabel jLblKolicina;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItemOdjava;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblPrijemnice;
    // End of variables declaration//GEN-END:variables
    public void uPozadini(){
        try {
            jLabelImeRadnika.setText(radnik.getIme());
            jLabelPrezimeRadnika.setText(radnik.getPrezime());
            jLabelKorisnickoImeRadnika.setText(radnik.getKorisnickoIme());
            ArrayList<Racun> stanje=(ArrayList<Racun>) CommunicationController.getInstance().vratiTrenutnoStanje();
            TableModel model=new TableModelPrijemnica(stanje);
            tblPrijemnice.setModel(model);
            jLblKolicina.setText(stanje.size()+"");
        } catch (IOException ex) {
            Logger.getLogger(frmMenu.class.getName()).log(Level.SEVERE, null, ex);
        }
    } 
}
