/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import domain.Prijemnica;
import java.util.Date;
import controller.Controller;
import domain.Racun;
import java.math.BigDecimal;
import javax.swing.JOptionPane;

/**
 *
 * @author Stefan
 */
public class frmStampajPrijemnicu extends javax.swing.JPanel {
    Prijemnica prijemnica;
    /**
     * Creates new form frmStampajPrijemnicu
     */
    public frmStampajPrijemnicu(Prijemnica prijemnica) {
        initComponents();
        this.prijemnica=prijemnica;
        uPozadini();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLblIme = new javax.swing.JLabel();
        jLblPrezime = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLblJMBG = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLblNaziv = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLblTezina = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLblLomljivost = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLblDatum = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLblUsername = new javax.swing.JLabel();
        jBtnStampajPrijemnicu = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        jLblDatumDanas = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLblCena = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/profile.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("DialogInput", 1, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Prijemnica");

        jLabel3.setFont(new java.awt.Font("DialogInput", 1, 16)); // NOI18N
        jLabel3.setText("Ime klijenta:");

        jLblIme.setFont(new java.awt.Font("DialogInput", 1, 16)); // NOI18N
        jLblIme.setText("Ime klijenta:");

        jLblPrezime.setFont(new java.awt.Font("DialogInput", 1, 16)); // NOI18N
        jLblPrezime.setText("Ime klijenta:");

        jLabel6.setFont(new java.awt.Font("DialogInput", 1, 16)); // NOI18N
        jLabel6.setText("Prezime klijenta:");

        jLblJMBG.setFont(new java.awt.Font("DialogInput", 1, 16)); // NOI18N
        jLblJMBG.setText("Ime klijenta:");

        jLabel8.setFont(new java.awt.Font("DialogInput", 1, 16)); // NOI18N
        jLabel8.setText("JMBG klijenta:");

        jLblNaziv.setFont(new java.awt.Font("DialogInput", 1, 16)); // NOI18N
        jLblNaziv.setText("Ime klijenta:");

        jLabel10.setFont(new java.awt.Font("DialogInput", 1, 16)); // NOI18N
        jLabel10.setText("Naziv:");

        jLblTezina.setFont(new java.awt.Font("DialogInput", 1, 16)); // NOI18N
        jLblTezina.setText("Ime klijenta:");

        jLabel12.setFont(new java.awt.Font("DialogInput", 1, 16)); // NOI18N
        jLabel12.setText("Tezina:");

        jLblLomljivost.setFont(new java.awt.Font("DialogInput", 1, 16)); // NOI18N
        jLblLomljivost.setText("Ime klijenta:");

        jLabel14.setFont(new java.awt.Font("DialogInput", 1, 16)); // NOI18N
        jLabel14.setText("Lomljivost:");

        jLabel15.setFont(new java.awt.Font("DialogInput", 1, 16)); // NOI18N
        jLabel15.setText("Datum prijema:");

        jLblDatum.setFont(new java.awt.Font("DialogInput", 1, 16)); // NOI18N
        jLblDatum.setText("Ime klijenta:");

        jLabel16.setFont(new java.awt.Font("DialogInput", 1, 16)); // NOI18N
        jLabel16.setText("Radnik:");

        jLblUsername.setFont(new java.awt.Font("DialogInput", 1, 16)); // NOI18N
        jLblUsername.setText("Ime klijenta:");

        jBtnStampajPrijemnicu.setFont(new java.awt.Font("DialogInput", 1, 14)); // NOI18N
        jBtnStampajPrijemnicu.setText("Kreiraj racun");
        jBtnStampajPrijemnicu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnStampajPrijemnicuActionPerformed(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("DialogInput", 1, 16)); // NOI18N
        jLabel17.setText("Datum predavanja:");

        jLblDatumDanas.setFont(new java.awt.Font("DialogInput", 1, 16)); // NOI18N
        jLblDatumDanas.setText("Ime klijenta:");

        jLabel18.setFont(new java.awt.Font("DialogInput", 1, 16)); // NOI18N
        jLabel18.setText("Cena");

        jLblCena.setFont(new java.awt.Font("DialogInput", 1, 16)); // NOI18N
        jLblCena.setText("Ime klijenta:");

        jLabel4.setFont(new java.awt.Font("DialogInput", 1, 14)); // NOI18N
        jLabel4.setText("RSD");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(68, 68, 68)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel10)
                    .addComponent(jLabel14)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jBtnStampajPrijemnicu, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel17)
                                    .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.LEADING))
                                .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.LEADING))
                            .addGap(18, 18, 18)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLblDatum)
                                .addComponent(jLblDatumDanas)
                                .addComponent(jLblLomljivost)
                                .addComponent(jLblTezina)
                                .addComponent(jLblNaziv))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel6)
                                        .addComponent(jLabel3)
                                        .addComponent(jLabel8))
                                    .addGap(40, 40, 40)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLblJMBG)
                                        .addComponent(jLblIme)
                                        .addComponent(jLblPrezime)))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel16)
                                    .addGap(106, 106, 106)
                                    .addComponent(jLblUsername))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(22, 22, 22)
                                    .addComponent(jLabel18)
                                    .addGap(18, 18, 18)
                                    .addComponent(jLblCena, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jLabel4))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(jLabel16)
                            .addComponent(jLblUsername)
                            .addComponent(jLblNaziv))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(jLblTezina))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(jLblLomljivost)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jLblIme))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jLblPrezime))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(jLblJMBG))))
                .addGap(8, 8, 8)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLblCena, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel18)
                        .addComponent(jLabel4))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLblDatum)
                        .addComponent(jLabel15)))
                .addGap(4, 4, 4)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLblDatumDanas)
                    .addComponent(jLabel17))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addComponent(jBtnStampajPrijemnicu, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnStampajPrijemnicuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnStampajPrijemnicuActionPerformed
        if(Controller.getInstance().preuzetaPrijemenica(prijemnica)){
            Racun racun=new Racun();
            racun.setCena(new BigDecimal(jLblCena.getText().toString()));
            racun.setDatum(new Date());
            racun.setIdRacuna(new Long(0));
            racun.setKlijent(prijemnica.getKlijent());
            racun.setPrtljag(prijemnica.getPrtljag());
            racun.setRadnik(prijemnica.getRadnik());
            Controller.getInstance().kreirajRacun(racun);
            JOptionPane.showMessageDialog(this,"Uspesno ste kreirali racun!");
            
        }
        
    }//GEN-LAST:event_jBtnStampajPrijemnicuActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnStampajPrijemnicu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLblCena;
    private javax.swing.JLabel jLblDatum;
    private javax.swing.JLabel jLblDatumDanas;
    private javax.swing.JLabel jLblIme;
    private javax.swing.JLabel jLblJMBG;
    private javax.swing.JLabel jLblLomljivost;
    private javax.swing.JLabel jLblNaziv;
    private javax.swing.JLabel jLblPrezime;
    private javax.swing.JLabel jLblTezina;
    private javax.swing.JLabel jLblUsername;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
    public void uPozadini(){
        jLblIme.setText(prijemnica.getKlijent().getIme());
        jLblPrezime.setText(prijemnica.getKlijent().getPrezime());
        jLblJMBG.setText(prijemnica.getKlijent().getJMBG());
        jLblLomljivost.setText(prijemnica.getPrtljag().isLomljivo()+"");
        jLblTezina.setText(prijemnica.getPrtljag().getTezina()+" Kg");
        jLblDatum.setText(prijemnica.getDatum()+"");
        jLblDatumDanas.setText(new Date()+"");
        jLblNaziv.setText(prijemnica.getPrtljag().getNaziv()+"");
        jLblUsername.setText(prijemnica.getRadnik().getKorisnickoIme());
        long period=new Date().getTime()-prijemnica.getDatum().getTime();
        double cena=(period/1000) *100;
        jLblCena.setText(cena+"");
    }
}
